trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'
    jdkArchitecture: 'x64'

- task: CacheBeta@1
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    path: '$(Pipeline.Workspace)/.m2/repository'
    cacheHitVar: 'MavenCacheHit'
    displayName: 'Cache Maven packages'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
  condition: ne(variables.MavenCacheHit, 'true')
  displayName: 'Build with Maven'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
  condition: eq(variables.MavenCacheHit, 'true')
  displayName: 'Build with cached Maven packages'

- script: |
    java -cp target/myapp-1.0-SNAPSHOT.jar HelloWorld
  displayName: 'Run Hello World'
